_target_: src.models.mri_calgary_campinas_module.MRI_Calgary_Campinas_LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0003
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.utils.direct_adaptors.varnet_engine.EndToEndVarNetEngine
  model:
    _target_: src.utils.direct.nn.varnet.varnet.EndToEndVarNet
    forward_operator:
      _partial_: true
      _target_: src.utils.direct.data.transforms.fft2
      centered: False
      normalized: False
    backward_operator:
      _partial_: true
      _target_: src.utils.direct.data.transforms.ifft2
      centered: False
      normalized: False
    num_layers: 12
  forward_operator:
    _partial_: true
    _target_: src.utils.direct.data.transforms.fft2
    centered: False
    normalized: False
  backward_operator:
    _partial_: true
    _target_: src.utils.direct.data.transforms.ifft2
    centered: False
    normalized: False
  sensitivity:
    _target_: src.utils.direct.data.mri_transforms.EstimateSensitivityMapModule
    backward_operator:
      _partial_: true
      _target_: src.utils.direct.data.transforms.ifft2
      centered: False


# compile model for faster training with pytorch 2.0
compile: false

criterions:
  mse:
    _target_: torch.nn.MSELoss
#  ssim:
#    _target_: src.models.components.losses.SSIMLoss
#
#criterion_2:
#    _target_: torch.nn.L1Loss


