_target_: src.models.mri_direct_module.MRI_Direct_LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.direct_adaptors.recurrentvarnet.recurrentvarnet_adaptor.RecurrentVarNetAdaptor
  num_steps: 10
  recurrent_hidden_channels: 8
  recurrent_num_layers: 2
  no_parameter_sharing: False


# compile model for faster training with pytorch 2.0
compile: false
