# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.EarlyStopping.html

learning_rate_logger:
  _target_: lightning.pytorch.callbacks.LearningRateLogger
  logging_interval: 'step'